on: 
  push:
    branches: [ "main" ]
    paths: [ "*.csproj" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build a project
      run: dotnet build
    - name: Get project's version
      id: project-info
      run: echo "VERSION=$(sed -n 's/.*<Version>\([0-9]\+\.[0-9]\+\)<\/Version>.*/\1/p' RetailCorrector.PluginAPI.csproj)" >> $GITHUB_OUTPUT
    - name: Register release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.project-info.outputs.VERSION }}
        name: ${{ steps.project-info.outputs.VERSION }}
        make_latest: true
    - name: Publish to NuGet
      run: dotnet nuget push "bin/Debug/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json"